docs: Add CommonJS plugin in example as it's required in most cases
If rollup-plugin-commonjs is not used, rollup complains:

  Error: 'default' is not exported by node_modules/vue-runtime-helpers/dist/normalize-component.js